### ISSUE TITLE
BT with PP JS SDK codepen

### ISSUE THREAD

**Issue by chadhoffman** [paypal/integration-packs#3]
integration-packs/codepen-samples/braintree-client-sdk.md 
Under 'Wallet Payment Methods:' the first link for 'PayPal' goes to this codepen: https://codepen.io/the_tfulton/pen/wvveGKZ
It is for 'Braintree with PayPal JavaScript SDK'
Unfortunately it uses the Vertical button but does not load the PP JS with 'disable-funding=card' so the Standard Card button is being displayed.
BT PP wallet examples should use Standalone Buttons, not the Vertical or Horizontal Buttons as a best practice.

**Comment by ksuralta** [comment]
Hi @chadhoffman , thanks for the feedback.  I have updated the CodePen link to https://codepen.io/ksuralta/pen/qBmPYYd which has cards disabled.
